apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cgpfvij9j-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cgpfvij9j-java-springboot-gitops